In [1]:
import numpy as np

In [2]:
test_array = np.zeros((3,3,3), dtype=np.uint8)
test_array2 = np.zeros((3,3,3), dtype=np.uint8)
test_array[1,2,1] = 1
test_array2[2,2,2] = 1
test_goal = [0,0,0]
print(test_array)

In [3]:
mask1 = (test_array == test_goal).all(-1)
mask2 = (test_array2 == test_goal).all(-1)

In [4]:
print(mask1)

In [5]:
print(mask2)

In [6]:
maskes = np.zeros((3,3,2), dtype=np.uint8)
maskes[:,:, 0] = mask1
maskes[:, :, 1] = mask2

print(maskes)

In [7]:
#mask = (test_array == [0,1,0]).all(-1)

In [8]:
#print(mask)

In [9]:
#mask = (test_array == [0,0,0]).all(-1)

In [10]:
maskes = maskes.astype(np.uint8)
print(maskes)
print(maskes.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [0 1]]

 [[1 1]
  [1 1]
  [1 0]]]
(3, 3, 2)


In [11]:
labels = np.zeros((3,3,3), dtype=np.uint8)

In [12]:
classes_cc = { #cc = carla cityScape
    0: [9, 8, 7],        # None
    1: [1, 2, 3],     # Buildings
    #2: [190, 153, 70],  # Fences
}

    
for key, value in classes_cc.items():
    mask = maskes[:,:, key]
    #print(mask)
    #print(value)
    #print(mask[:,:,None]*value)
    label = mask[... ,None] * value

#to_array[:,:,:] = mask * classes_cc[2]
print()
print('Ressults')  
print(labels)


Ressults
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [13]:
print(labels[0] + labels[1])

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
test_math = maskes[..., 0]
print(test_math)

[[1 1 1]
 [1 1 0]
 [1 1 1]]


In [15]:
print(test_math*[110, 215, 40])
#må plusses inn sideslengs ikke rett inn, test under!!

[[110 215  40]
 [110 215   0]
 [110 215  40]]


In [16]:
labels = np.zeros((3,3,3), dtype=np.uint8)

In [17]:
mask =  test_math[..., None]* [110, 215, 40]
print(mask)
labels[:,:,:] = labels[:,:,:] + mask 

[[[110 215  40]
  [110 215  40]
  [110 215  40]]

 [[110 215  40]
  [110 215  40]
  [  0   0   0]]

 [[110 215  40]
  [110 215  40]
  [110 215  40]]]


In [18]:
print(labels)

[[[110 215  40]
  [110 215  40]
  [110 215  40]]

 [[110 215  40]
  [110 215  40]
  [  0   0   0]]

 [[110 215  40]
  [110 215  40]
  [110 215  40]]]
